version: 2
updates:
  - package-ecosystem: 'composer'
    directory: '/'
    versioning-strategy: lockfile-only
    schedule:
      interval: 'weekly'
    groups:
      dependencies:
        patterns:
          - '*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
